export { crearEvento, crearPonente, ponentesDe } from './directorio'
export type { ResultadoEvento, ResultadoPonente } from './directorio'
export { crearEventoRemoto, crearPonenteRemoto, listarDirectorio } from './repositorio'
export { useDirectorio } from './useDirectorio'
export type { ValorDeDirectorio } from './useDirectorio'
