export { CLAVE_TAXONOMIA, guardarTaxonomia, leerTaxonomia } from './almacenamiento'
export type { Taxonomia, Tema, TemaActivoEnEvento, TemaPropuesto } from './data'
export { TAXONOMIA_DE_EJEMPLO, TEMAS_DE_EJEMPLO } from './data'
export type { ResultadoDeTaxonomia } from './taxonomia'
export { aprobarPropuesta, nombreDeTema, rechazarPropuesta } from './taxonomia'
export type { ResultadoDeAccion, ValorDeTaxonomia } from './useTaxonomia'
export { useTaxonomia } from './useTaxonomia'
